export const hospitalData = {
  about: {
    name: "Rumah Sakit Muhammadiyah Bandung Selatan",
    shortName: "RSMBS",
    tagline: "Layanan Kesehatan PRIMA Islami",
    taglineHash: "#RSMBSPRIMA",
    accreditation: "LARSI Paripurna — Standar Akreditasi Tertinggi RS Indonesia",
    type: "Rumah Sakit Umum Swasta Tipe B",
    address: "Jl. Raya Laswi, Ciheulang, Kec. Ciparay, Kabupaten Bandung, Jawa Barat 40375",
    phone: "(022) 86023290",
    igd: "(022) 86023290",
    email: "info@rsmbs.ac.id",
    website: "https://architechlabs-rsmbs.netlify.app/",
    whatsapp: "0811-2222-2986",
    whatsappFull: "+6281122222986",
    facebook: "https://www.facebook.com/rsmbsofficial/",
    instagram: "https://www.instagram.com/rsmbsofficial/",
    googleRating: "4.1",
    totalReviews: "459",
    totalDoctors: "141",
    totalBeds: "200+",
    operationalHours: "Buka 24 Jam (termasuk hari libur)",
    organization: "Persyarikatan Muhammadiyah",
    values: "PRIMA — Profesional, Ramah, Islami, Modern, Amanah",
  },

  registration: {
    channels: [
      {
        name: "WhatsApp (Paling Cepat & Direkomendasikan)",
        contact: "0811-2222-2986",
        link: "https://wa.me/6281122222986",
        hours: "Senin–Sabtu 07.00–20.00",
        note: "Ketik: nama lengkap, tanggal lahir, poli/dokter yang dituju, tanggal preferensi"
      },
      {
        name: "Telepon",
        contact: "(022) 86023290",
        hours: "24 jam (untuk IGD), pendaftaran 07.00–19.00",
        note: "Hubungi loket pendaftaran"
      },
      {
        name: "Datang Langsung",
        location: "Loket Pendaftaran, Lt. 1 RSMBS",
        hours: "Senin–Jumat 07.00–19.00 | Sabtu 07.00–14.00",
        note: "Bawa identitas (KTP/KK) dan kartu BPJS (jika ada)"
      }
    ],
    steps: [
      "1️⃣ Pilih cara daftar: WhatsApp, telepon, atau datang langsung",
      "2️⃣ Siapkan: KTP/KK, kartu BPJS (jika BPJS), surat rujukan (jika BPJS/rawat jalan spesialis)",
      "3️⃣ Pilih poli/dokter spesialis dan tanggal kunjungan",
      "4️⃣ Dapatkan nomor antrian / konfirmasi jadwal",
      "5️⃣ Datang 15–30 menit sebelum jadwal, ambil nomor antrian di loket",
      "6️⃣ Tunggu panggilan, lalu masuk ke poli yang dituju"
    ],
    bpjsRequirements: [
      "Kartu BPJS Kesehatan aktif",
      "KTP/KK asli",
      "Surat rujukan dari Puskesmas/FKTP (untuk poliklinik spesialis)",
      "Surat Eligibilitas Peserta (SEP) — diterbitkan di loket RSMBS"
    ],
    generalRequirements: [
      "KTP atau kartu identitas lainnya",
      "Kartu asuransi swasta (jika ada)",
      "Surat pengantar dokter (jika dari dokter lain)"
    ],
    appointmentHours: {
      outpatient: "Senin–Jumat 07.00–20.00 | Sabtu 07.00–15.00",
      specialist: "Sesuai jadwal masing-masing dokter spesialis",
      emergency: "IGD buka 24 jam, tidak perlu daftar terlebih dahulu"
    }
  },

  // Catatan: data dokter HARUS sinkron dengan /doctors-data.js (frontend).
  // Saat update, ubah kedua file agar AI dan UI konsisten.
  doctors: [
    {
      name: "dr. Ahmad Fauzi, Sp.PD",
      slug: "ahmad-fauzi",
      specialist: "Penyakit Dalam",
      profileUrl: "/dokter.html?id=ahmad-fauzi",
      schedule: [
        { day: "Senin",  start: "08:00", end: "14:00" },
        { day: "Selasa", start: "08:00", end: "14:00" },
        { day: "Rabu",   start: "08:00", end: "14:00" },
        { day: "Kamis",  start: "08:00", end: "14:00" },
        { day: "Jumat",  start: "08:00", end: "11:30" },
      ],
      room: "Poliklinik Penyakit Dalam — Lt. 2",
      experienceYears: 18,
      expertise: ["Diabetes Mellitus", "Hipertensi", "Hepatitis", "Gangguan Pencernaan", "Kolesterol Tinggi"],
    },
    {
      name: "dr. Siti Rahmawati, Sp.A",
      slug: "siti-rahmawati",
      specialist: "Dokter Anak (Pediatri)",
      profileUrl: "/dokter.html?id=siti-rahmawati",
      schedule: [
        { day: "Senin",  start: "08:00", end: "13:00" },
        { day: "Selasa", start: "08:00", end: "13:00" },
        { day: "Rabu",   start: "08:00", end: "13:00" },
        { day: "Kamis",  start: "08:00", end: "13:00" },
        { day: "Jumat",  start: "08:00", end: "11:00" },
        { day: "Sabtu",  start: "08:00", end: "12:00" },
      ],
      room: "Poliklinik Anak — Lt. 2",
      experienceYears: 12,
      expertise: ["Tumbuh Kembang Anak", "Imunisasi", "Nutrisi Anak", "Demam Berdarah", "Asma Anak"],
    },
    {
      name: "dr. Budi Santoso, Sp.OG",
      slug: "budi-santoso",
      specialist: "Kandungan & Kebidanan",
      profileUrl: "/dokter.html?id=budi-santoso",
      schedule: [
        { day: "Selasa", start: "09:00", end: "14:00" },
        { day: "Rabu",   start: "09:00", end: "14:00" },
        { day: "Kamis",  start: "09:00", end: "14:00" },
        { day: "Jumat",  start: "09:00", end: "11:30" },
        { day: "Sabtu",  start: "09:00", end: "13:00" },
      ],
      room: "Poliklinik Kebidanan & Kandungan — Lt. 3",
      experienceYears: 20,
      expertise: ["Kehamilan Risiko Tinggi", "USG 4D", "Persalinan Normal & SC", "KB & Kontrasepsi", "Kista & Mioma"],
    },
    {
      name: "dr. Dewi Kartika, Sp.JP",
      slug: "dewi-kartika",
      specialist: "Jantung & Pembuluh Darah",
      profileUrl: "/dokter.html?id=dewi-kartika",
      schedule: [
        { day: "Senin",  start: "13:00", end: "18:00" },
        { day: "Selasa", start: "13:00", end: "18:00" },
        { day: "Rabu",   start: "13:00", end: "18:00" },
        { day: "Kamis",  start: "13:00", end: "18:00" },
        { day: "Jumat",  start: "13:00", end: "17:00" },
      ],
      room: "Poliklinik Jantung — Lt. 3",
      experienceYears: 15,
      expertise: ["Hipertensi", "Penyakit Jantung Koroner", "Aritmia", "Gagal Jantung", "EKG & Echocardiography"],
    },
    {
      name: "dr. Rizky Pratama, Sp.BS",
      slug: "rizky-pratama",
      specialist: "Bedah Saraf",
      profileUrl: "/dokter.html?id=rizky-pratama",
      schedule: [
        { day: "Senin", start: "09:00", end: "14:00" },
        { day: "Rabu",  start: "09:00", end: "14:00" },
        { day: "Jumat", start: "09:00", end: "12:00" },
      ],
      room: "Poliklinik Bedah — Lt. 3",
      experienceYears: 14,
      expertise: ["Cedera Kepala", "Tumor Otak", "Saraf Terjepit (HNP)", "Hidrosefalus", "Operasi Tulang Belakang"],
    },
    {
      name: "dr. Nurul Hidayah, Sp.N",
      slug: "nurul-hidayah",
      specialist: "Saraf (Neurologi)",
      profileUrl: "/dokter.html?id=nurul-hidayah",
      schedule: [
        { day: "Selasa", start: "09:00", end: "15:00" },
        { day: "Rabu",   start: "09:00", end: "15:00" },
        { day: "Kamis",  start: "09:00", end: "15:00" },
        { day: "Jumat",  start: "09:00", end: "11:30" },
      ],
      room: "Poliklinik Saraf — Lt. 2",
      experienceYears: 11,
      expertise: ["Stroke", "Migrain & Sakit Kepala", "Epilepsi", "Vertigo", "Gangguan Tidur"],
    },
    {
      name: "dr. Yoga Perdana, Sp.OT",
      slug: "yoga-perdana",
      specialist: "Ortopedi & Traumatologi",
      profileUrl: "/dokter.html?id=yoga-perdana",
      schedule: [
        { day: "Senin",  start: "10:00", end: "15:00" },
        { day: "Selasa", start: "10:00", end: "15:00" },
        { day: "Rabu",   start: "10:00", end: "15:00" },
        { day: "Kamis",  start: "10:00", end: "15:00" },
        { day: "Jumat",  start: "10:00", end: "11:30" },
        { day: "Sabtu",  start: "09:00", end: "13:00" },
      ],
      room: "Poliklinik Ortopedi — Lt. 3",
      experienceYears: 13,
      expertise: ["Patah Tulang", "Cedera Olahraga", "Penggantian Sendi (Lutut/Pinggul)", "Skoliosis", "Osteoporosis"],
    },
    {
      name: "dr. Maya Lestari, Sp.B",
      slug: "maya-lestari",
      specialist: "Bedah Umum",
      profileUrl: "/dokter.html?id=maya-lestari",
      schedule: [
        { day: "Selasa", start: "08:00", end: "13:00" },
        { day: "Rabu",   start: "08:00", end: "13:00" },
        { day: "Sabtu",  start: "08:00", end: "12:00" },
      ],
      room: "Poliklinik Bedah — Lt. 3",
      experienceYears: 16,
      expertise: ["Apendisitis", "Hernia", "Benjolan/Tumor Jinak", "Bedah Tiroid", "Bedah Laparoskopi"],
    },
    {
      name: "dr. Farhan Halim, Sp.M",
      slug: "farhan-halim",
      specialist: "Mata",
      profileUrl: "/dokter.html?id=farhan-halim",
      schedule: [
        { day: "Senin",  start: "09:00", end: "14:00" },
        { day: "Selasa", start: "09:00", end: "14:00" },
        { day: "Rabu",   start: "09:00", end: "14:00" },
        { day: "Kamis",  start: "09:00", end: "14:00" },
        { day: "Jumat",  start: "09:00", end: "11:30" },
        { day: "Sabtu",  start: "08:00", end: "12:00" },
      ],
      room: "Poliklinik Mata — Lt. 2",
      experienceYears: 10,
      expertise: ["Katarak", "Glaukoma", "Refraksi (Minus/Plus)", "Mata Merah", "LASIK Konsultasi"],
    },
    {
      name: "dr. Lina Kusuma, Sp.KK",
      slug: "lina-kusuma",
      specialist: "Kulit & Kelamin",
      profileUrl: "/dokter.html?id=lina-kusuma",
      schedule: [
        { day: "Senin",  start: "10:00", end: "15:00" },
        { day: "Selasa", start: "10:00", end: "15:00" },
        { day: "Rabu",   start: "10:00", end: "15:00" },
        { day: "Kamis",  start: "10:00", end: "15:00" },
        { day: "Jumat",  start: "10:00", end: "11:30" },
      ],
      room: "Poliklinik Kulit & Kelamin — Lt. 2",
      experienceYears: 9,
      expertise: ["Jerawat", "Eksim", "Psoriasis", "Infeksi Kulit", "Estetika Medis Dasar"],
    },
    {
      name: "dr. Rina Pratiwi, Sp.THT",
      slug: "rina-pratiwi",
      specialist: "THT (Telinga, Hidung, Tenggorokan)",
      profileUrl: "/dokter.html?id=rina-pratiwi",
      schedule: [
        { day: "Rabu",   start: "08:00", end: "13:00" },
        { day: "Kamis",  start: "08:00", end: "13:00" },
        { day: "Jumat",  start: "08:00", end: "11:30" },
        { day: "Sabtu",  start: "08:00", end: "12:00" },
        { day: "Minggu", start: "09:00", end: "12:00" },
      ],
      room: "Poliklinik THT — Lt. 2",
      experienceYears: 12,
      expertise: ["Sinusitis", "Tonsilitis", "Vertigo", "Gangguan Pendengaran", "Polip Hidung"],
    },
    {
      name: "dr. Yusuf Hakim, Sp.KJ",
      slug: "yusuf-hakim",
      specialist: "Kesehatan Jiwa (Psikiatri)",
      profileUrl: "/dokter.html?id=yusuf-hakim",
      schedule: [
        { day: "Senin",  start: "14:00", end: "18:00" },
        { day: "Selasa", start: "14:00", end: "18:00" },
        { day: "Rabu",   start: "14:00", end: "18:00" },
        { day: "Kamis",  start: "14:00", end: "18:00" },
        { day: "Jumat",  start: "14:00", end: "17:00" },
      ],
      room: "Poliklinik Kesehatan Jiwa — Lt. 4",
      experienceYears: 11,
      expertise: ["Depresi", "Gangguan Cemas", "Insomnia", "Stres Pekerjaan", "Konseling Pasangan"],
    },
  ],

  services: [
    "IGD 24 Jam dengan respon time < 5 menit",
    "ICU / ICCU / NICU (Neonatal ICU)",
    "Kamar Operasi — termasuk operasi jantung",
    "Hemodialisis (Cuci Darah)",
    "Kemoterapi Rawat Jalan",
    "Laboratorium Klinik & Patologi Anatomi (buka setiap hari 06.00–22.00)",
    "Radiologi: X-Ray, USG, CT Scan 128-slice, MRI 1.5 Tesla",
    "Endoskopi & Kolonoskopi",
    "Fisioterapi & Rehabilitasi Medik",
    "Bank Darah RS",
    "Apotek 24 Jam",
    "Ambulans 24 Jam",
    "Poliklinik Umum & Spesialis (18 poli)",
    "Medical Check-Up (MCU) — Paket Reguler & Eksekutif",
    "Layanan BPJS Kesehatan",
    "Vaksinasi (Influenza, HPV, dll)",
    "Konsultasi Gizi Klinik",
  ],

  rooms: {
    paviliun: { name: "Paviliun", desc: "Suite eksklusif, AC, TV, sofa keluarga, fasilitas premium", tariff: "Hubungi RS untuk info tarif", capacity: 10 },
    vip: { name: "VIP", desc: "Kamar pribadi, AC, TV, sofa keluarga, wifi", tariff: "Hubungi RS untuk info tarif", capacity: 25 },
    kelas1: { name: "Kelas I", desc: "Kamar 2 bed, AC, TV, wifi", tariff: "Hubungi RS untuk info tarif", capacity: 40 },
    kelas2: { name: "Kelas II", desc: "Kamar 4 bed, AC, wifi", tariff: "Sesuai tarif BPJS/RS", capacity: 50 },
    kelas3: { name: "Kelas III", desc: "Kamar 6 bed, AC, wifi", tariff: "Sesuai tarif BPJS/RS", capacity: 80 },
    bpjs: { name: "Kelas BPJS (I/II/III)", desc: "Sesuai hak kelas BPJS peserta", tariff: "Gratis sesuai ketentuan BPJS Kesehatan", capacity: 100 },
  },

  schedules: {
    outpatient: "Senin–Jumat 07.00–20.00 | Sabtu 07.00–15.00",
    specialist: "Senin–Sabtu, sesuai jadwal masing-masing dokter",
    inpatient: "24 Jam",
    emergency: "24 Jam (setiap hari, termasuk hari libur)",
    pharmacy: "24 Jam",
    laboratory: "Setiap hari 06.00–22.00",
    radiology: "Setiap hari 07.00–21.00",
    registration: "Senin–Jumat 07.00–19.00 | Sabtu 07.00–14.00",
  },

  insurance: {
    bpjs: true,
    bpjsNote: "RSMBS adalah FKTL (Fasilitas Kesehatan Tingkat Lanjut) mitra BPJS Kesehatan. Wajib membawa kartu BPJS aktif + surat rujukan dari Puskesmas/FKTP.",
    swasta: ["Prudential", "AIA", "Allianz", "Manulife", "AXA Mandiri", "Lippo Insurance", "Inhealth", "Generali", "Sinarmas"],
    payment: ["Tunai", "Kartu Debit", "Kartu Kredit (Visa/Mastercard)", "Transfer Bank (BCA, BRI, BNI, Mandiri, BJB)", "QRIS", "GoPay", "OVO"],
  },

  location: {
    address: "Jl. Raya Laswi, Ciheulang, Kec. Ciparay, Kabupaten Bandung, Jawa Barat 40375",
    landmark: "Dekat Pasar Ciparay, di Jalan Raya Laswi arah Majalaya",
    googleMaps: "https://maps.google.com/?q=Rumah+Sakit+Muhammadiyah+Bandung+Selatan",
    parking: "Tersedia parkir luas di area RS",
  },

  // Sinkron dengan /jobs-data.js (frontend). Update bersamaan saat ada perubahan.
  career: {
    pageUrl: "/karir.html",
    contactEmail: "hrd@rsmbs.ac.id",
    contactWhatsApp: "0811-2222-2986",
    officeHours: "Senin–Jumat 08:00–15:00 (HRD Lt. 4)",
    totalOpenings: 12,
    applicationProcess: [
      "Siapkan berkas: CV, ijazah, transkrip, KTP, pas foto, STR/SIP (medis), sertifikat pendukung, surat lamaran",
      "Kirim via email hrd@rsmbs.ac.id atau WA 0811-2222-2986 (atau datang langsung HRD Lt. 4)",
      "Seleksi administrasi (1 minggu)",
      "Tes tertulis & wawancara HRD (minggu ke-2)",
      "Wawancara user & medical check-up (minggu ke-3)",
      "Penawaran & onboarding (minggu ke-4)",
    ],
    openPositions: [
      { title: "Dokter Spesialis Anak (Sp.A)",   category: "medis",      department: "Poliklinik Anak",        type: "Full-time",         deadline: "31 Mei 2026",   urgent: true,  url: "/karir.html#dokter-spesialis-anak" },
      { title: "Dokter Umum (IGD)",              category: "medis",      department: "IGD 24 Jam",             type: "Full-time / Shift", deadline: "25 Mei 2026",   urgent: true,  url: "/karir.html#dokter-umum-igd" },
      { title: "Perawat ICU",                    category: "medis",      department: "ICU / ICCU",             type: "Full-time / Shift", deadline: "30 Mei 2026",   urgent: false, url: "/karir.html#perawat-icu" },
      { title: "Perawat Umum",                   category: "medis",      department: "Rawat Inap & Jalan",     type: "Full-time / Shift", deadline: "31 Mei 2026",   urgent: false, url: "/karir.html#perawat-umum" },
      { title: "Bidan",                          category: "medis",      department: "Poli Kebidanan & VK",    type: "Full-time",         deadline: "30 Mei 2026",   urgent: false, url: "/karir.html#bidan" },
      { title: "Apoteker",                       category: "penunjang",  department: "Instalasi Farmasi",      type: "Full-time",         deadline: "28 Mei 2026",   urgent: false, url: "/karir.html#apoteker" },
      { title: "Analis Laboratorium",            category: "penunjang",  department: "Laboratorium Klinik",    type: "Full-time / Shift", deadline: "5 Juni 2026",   urgent: false, url: "/karir.html#analis-laboratorium" },
      { title: "Radiografer",                    category: "penunjang",  department: "Radiologi",              type: "Full-time",         deadline: "10 Juni 2026",  urgent: false, url: "/karir.html#radiografer" },
      { title: "Fisioterapis",                   category: "penunjang",  department: "Rehabilitasi Medik",     type: "Full-time",         deadline: "15 Juni 2026",  urgent: false, url: "/karir.html#fisioterapis" },
      { title: "Customer Service",               category: "non-medis",  department: "Pelayanan Pelanggan",    type: "Full-time",         deadline: "31 Mei 2026",   urgent: false, url: "/karir.html#customer-service" },
      { title: "IT Support",                     category: "non-medis",  department: "IT & SIM RS",            type: "Full-time",         deadline: "28 Mei 2026",   urgent: false, url: "/karir.html#it-support" },
      { title: "Staff Akuntansi",                category: "non-medis",  department: "Keuangan",               type: "Full-time",         deadline: "1 Juni 2026",   urgent: false, url: "/karir.html#akuntan" },
    ],
  },
};
